settings:
  title: 'Status Page'
  url: 'https://status.lgbt.sh' # used for Slack messages
  #logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 365 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: lgbt-sh # unique identifier
    name: lgbt.sh
    description: 'The main landing page' # default=empty
    url: 'https://lgbt.sh/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: blog-lgbt-sh
    name: Personal Blog
    description: 'My little diary'
    url: 'https://blog.lgbt.sh/'
    method: GET
    expectStatus: 200

  - id: hrt-info
    name: HRT.info
    description: 'Work in progress HRT information site'
    url: 'https://hrt.info'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  
  - id: HWU
    name: Harmony Within Us
    description: 'Landing site of HWU'
    url: 'https://harmony-within.us'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: testing
    name: Testing website
    description: 'Not really in use'
    url: 'http://app.xn--q9jyb4c/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  

  

